services:
  db:
    image: ankane/pgvector:latest
    container_name: sentinel-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tickers"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: tickers
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    networks:
      - sentinel-network


  redis:
    image: redis/redis-stack:latest
    container_name: sentinel-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sentinel-network


  app:
    build: .
    container_name: sentinel-app
    command: > 
      sh -c "python manage.py migrate && 
      streamlit run frontend/script.py --server.address=0.0.0.0 --server.port=8501"


    ports:
      - "8501:8501"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - sentinel-network




networks:
  sentinel-network:
    driver: bridge
