# Generated by Django 6.0.3 on 2026-04-08 19:53

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=768)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tickers.news')),
            ],
            options={
                'verbose_name': 'Embedding',
                'verbose_name_plural': 'Embeddings',
            },
        ),
    ]
